# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blog Fabian Reinhard
tagline:             'Liberaler Blog'
description:         'Fabian Reinhard: IT-Unternehmer, Grossstadtrat Luzern, Pr√§sident FDP.die Liberalen Stadt Luzern'
url:                 http://www.fabianreinhard.ch
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Fabian Reinhard
  url:               https://twitter.com/fabianreinhard
  email:             fabian@reinhard.ch

# Custom vars
version:             1.0.0
